# Generated by Django 4.0.1 on 2022-02-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Events', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('p_contact', models.CharField(max_length=50)),
                ('p_date', models.DateField(verbose_name='Date')),
                ('p_time', models.TimeField(verbose_name='Time')),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProject.planner')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProject.venue')),
            ],
        ),
    ]
