# Generated by Django 4.0.1 on 2022-02-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue',
            new_name='Ven',
        ),
    ]
